### ISSUE TITLE
Add a converter for Immersive Engineering multiblocks

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/Architect#12]
All of the simple ones can be handled by white listing, but the multiblock stuff will need a custom converter.

**Comment by calloatti** [comment]
My 2c: Not worth the trouble, you can use a non-hammer hit multiblock model as your source. Also, blueprints can be shared to even save that step.

**Comment by fnuecke** [comment]
I might well spare me the trouble for those, true, but there's also the ones that auto-multiblock on placement, such as the watermill or the autoturrets. So at least for those it'd make sense I think.

**Comment by fnuecke** [comment]
cba
