### ISSUE TITLE
Building an Immersive Engineering Excavator using Architect

### ISSUE THREAD

**Issue by calloatti** [MightyPirates/Architect#13]
Start by using an existing excavator as your model:

![image](https://cloud.githubusercontent.com/assets/12817862/25360547/fa5b28dc-291f-11e7-9771-3bc17fbee0ab.png)

Break one block of the excavator and one block of the excavator wheel and put them right back to get the raw blocks, then dig a hole one block down in one corner, shift rclick with the sketch to set one corner:

![image](https://cloud.githubusercontent.com/assets/12817862/25360626/515c539a-2920-11e7-9fc6-a77037ff2a19.png)

We do this to include the excavator wheel blocks that are underground in the final blueprint:

![image](https://cloud.githubusercontent.com/assets/12817862/25360659/6aa5e938-2920-11e7-80e5-f073afae1d7e.png)

Now select the opposite top corner of the excavator and rclick to include all the blocks:

![image](https://cloud.githubusercontent.com/assets/12817862/25360730/bde2cd1e-2920-11e7-8408-27b21cc43d8e.png)

Do we have all the blocks selected? Maybe. The blue grid seems pointless and gets in the way, and the pale blue block highlights are hard to see. Maybe a config option to turn off the blue grid and a config option to change the selected block color highlight would be great. (bright yellow for example)

![image](https://cloud.githubusercontent.com/assets/12817862/25360827/306d67d6-2921-11e7-89ba-e3d9d2d60a6a.png)

Create the blueprint, and pick a spot to place the new excavator:

![image](https://cloud.githubusercontent.com/assets/12817862/25360870/6fbf15ec-2921-11e7-8138-4af3de11b631.png)

There is no way to select a spot in one block increments...

Dig a one block deep trench for the excavator wheel, and a 2 block deep hole for the excavator wheel thing in the middle of the trench:

![image](https://cloud.githubusercontent.com/assets/12817862/25360949/d8940758-2921-11e7-969b-4028329e2f00.png)

Now the tricky part: get on top to be able to shift mouse wheel to set the blueprint 2 blocks down. Click and watch in awe how the excavator gets built.

![image](https://cloud.githubusercontent.com/assets/12817862/25360976/fa314b28-2921-11e7-8297-a78b32ea92e2.png)

Check that the excavator wheel has been properly built:

![image](https://cloud.githubusercontent.com/assets/12817862/25361003/2332111a-2922-11e7-9452-c0a4561ce952.png)

Hit the thing with a hammer, add power, and watch it go:

![image](https://cloud.githubusercontent.com/assets/12817862/25361015/3ab7a05c-2922-11e7-9cee-235a5eb95e6a.png)

Success!:

![image](https://cloud.githubusercontent.com/assets/12817862/25361039/6132e3f4-2922-11e7-930c-347916d40a56.png)

Observations:

1. The blue grid should have a config option to turn it off. No idea why that grid exists in the first place.

2. The color of selected block (light blue) should be configurable/changed. You can barely see that blocks are actually selected (bright yellow would work)

3. You should be able to place the blueprint in one block increments, not in blueprint width/depth increments.

4. You should be able to pick a spot and shift click to place the blueprint, just like you shift click to select the start of a selection with the sketch. That way, in this case, instead of fiddling with shift mouse wheel to sink the blueprint 2 blocks, you just dig a hole one deep and shift click.

5. Dirt/stone blocks should be automatically replaced with the blueprint blocks and just dissapear? Avoids having to dig the trench (Not sure about this)

**Comment by calloatti** [comment]
IMMERSIVE ENGINEER EXCAVATOR BLUEPRINT: (Includes dirt blocks)

H4sIAAAAAAAAAM2TvU7DQAzH3fTy0YBgRqoECztITJ1QxYIEU5/glLrpSeSC7k5dWXgBVt6ARwGJhcfgCRg6cA05akI7VKlOtWTZSvz3z46VFKAHbMwNT8GmDPazUs5QGVQ3o+Hz5dfnxevRY/pT0gFWoOGQAJO8QDgohMRM8YkZjIUyQNW3o+HJy9v8o3/9Dpt1PVx2zRXXul3bxLXti6JApcUMUeaWgErIfKBNqXiO7RgdxzhdyViU3F1hZklGlPK8HYxtBDtrBwt9wn5Pdbz6VFNEUxHbYWKfO3W3BNuDVOEEFcoMtf1TC1hah3gAf809W8Qu8YC8B/K+WcfqGJI8qiM0+qzTB2v025qBmusZkTqaxyRvfis6S1SzXB2rtWyFxllMeEk9b0RixCDUUzExNn+YV7BElaa6vBX37kstFrm9b/fJDUqX8mlx7UHDffOp7wLf1wy7ur9vfkiiT/u//zcXKsRKKwkAAA==

**Comment by fnuecke** [comment]
Thanks for the feedback!

1. The grid exists to make placing stuff like wall segments next to each other quicker. Might be a good idea to add a hotkey to turn off the main grid though.

2. Fair point, might even couple that to the blueprint's color (the one that can be changed the sneak-rclick UI). Though that'd probably make black utterly useless as a marking color :P

3. You can! While sneaking, scroll the mouse-wheel up or down to shift blockwise along the axis you're (primarily) looking along.

4. Wait, you knew about the sneak-wheel? Then I don't get 3 in addition to 1. Shift click... hmm, shift left click is still free. Though I'm not quite sure I understand what you mean; this as an alternative to the sneak-wheeling, yes? So quickly setting the grid offset via that? I'll test this out.

5. Removal is... potentially dangerous I think. And where to draw the line. Just dirt and smooth stone? Cobble? All the different Minecraft stone variants? Marble from whatever mods add it? Would probably need an extra JSON config file. If it's straight up replacement, so that it can't be abused as way too powerful mining... I might be allright with this. Air blocks in the blueprint would never clear away existing blocks though, exactly because of that, so I'm not sure of the general usefulness given that.

So, for now:
- [x] Add option / keybind to toggle the grid-snapping of blueprints.
- [x] Add a way to change blueprint placement indication color.

**Comment by calloatti** [comment]
Thanks for responding. Great mod by the way, I love it already.

1. That would be great.

2. Great too.

3. I get that, but then the blocks are displaced relative to the green wireframe. (why do we have that green wireframe in the first place?? Only to indicate rotation of the model with the green plane? Makes the placing UI kind of messy and confusing, at least for me. How about just displaying a "Rotation: 0/90/180/270° text and getting rid of the green wireframe that only makes things more confusing  when you used shift wheel and moved blocks around (and that even persists across uses).

4. What I mean is you lets say shift left click on a block and that means "place the blocks starting here using the currently selected rotation. No xyz block displacements, start right here in this corner and build going up and away from me."

5. Yes, the implications, that is why I had my doubts about this one.

**Comment by fnuecke** [comment]
3. Oh, you mean the filled rectangle indicating the "forward" direction. Hmm. I can at least make it a little more subtle. I prefer a visual indicator over a textual one. I'll see if I can come up with something better.

4. Ah. But wouldn't that be solved by being able to disable the grid? At least I'd think that's how it'd work with no grid anyway.

**Comment by fnuecke** [comment]
36e7b6e5429253c0ba69a9a862fc5c77f793c76d

All right, did a bunch of tweaking. I'm pretty happy with it now. Going through review on Curse now. 4 is a bit different; non-snapping is now always centered, but sneak-scroll in non-snapping mode allows adjusting the placement distance, similar to the selection distance in the sketch, so i think that's fine.

Moving 5 to a dedicated issue.
