### ISSUE TITLE
Blueprint by default gets placed 2 blocks below ground level

### ISSUE THREAD

**Issue by calloatti** [MightyPirates/Architect#14]
Trying to create a blueprint for an IE Tank, shift right click with sketch to select starting block:

![image](https://cloud.githubusercontent.com/assets/12817862/25361755/4eea287a-2926-11e7-8347-4513e67655eb.png)

Now select top opposite corner block of tank:

![image](https://cloud.githubusercontent.com/assets/12817862/25361777/61cd04bc-2926-11e7-92b4-da9b7010bad4.png)

Create blueprint and try to place it. It gets placed 2 blocks below  ground level (why?):

![image](https://cloud.githubusercontent.com/assets/12817862/25362387/ffdc51fa-2929-11e7-83e3-26ffddfb9b17.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25361810/8daaf6a2-2926-11e7-939e-4c6777a3e1dd.png)

Make a 2 block deep hole for the tank:

![image](https://cloud.githubusercontent.com/assets/12817862/25361824/a41a0ca2-2926-11e7-9640-de63683cdfd4.png)

Not the ideal situation, but this works.

What should happen: Blueprint should start over the block the user is pointing at, not 2 blocks down.

**Comment by fnuecke** [comment]
That's because the main grid always starts at the origin. So your y-level is just 2 above a multiple of the vertical grid size. Mm, I think I'll just adjust the initially stored sneak-scroll-shift to be such that the blueprint would be placed at the original sketch location.

**Comment by fnuecke** [comment]
441b8c640ab40d6bb09ec9aa8b1357377a8eb1af
