### ISSUE TITLE
Get rid of absolute coordinate references

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/Architect#18]
Playing a mod pack in which all references to Minecraft's coordinate system are removed, it was noticed that this mod does show some in various places. Given the nature of this mod, I think there could be better ways of displaying that information. My suggestion would be displaying the (cartesian?) distance to the structure/bound position and width/height of the structure; that information itself should be more useful to builders than the exact position anyway.

**Comment by fnuecke** [comment]
Fair enough. I'll still show it in advanced mode for convenience (F3+H). Since there's out-of-character stuff like NBT info in there I don't think there's much of an argument to be made against that?

**Comment by fnuecke** [comment]
ee3cfcd7316714687b453e8892c93ff3f6807e91

**Comment by CovertJaguar** [comment]
The providers also display coordinates.

**Comment by fnuecke** [comment]
Taken care of!
