### ISSUE TITLE
Config option for larger selections

### ISSUE THREAD

**Issue by Jomik** [MightyPirates/Architect#27]
Title says it all. I'd like to be able to select larger things. Like, a 17x7x17 Blood Altar build 😄 

Can be closed if this is intentional. I'll just have to cut it in quarters 😄

**Comment by fnuecke** [comment]
Yeah, sorry, you'll have to use multiple blueprints :/

It's partially for balancing reasons (for anything much larger, there's still stuff like the Buldcraft Builder e.g.), but partly it's also me not wanting to cram much more data into one item -- data that has to be synced to the client whenever the item stack is synced to the client!
