### ISSUE TITLE
 1.12-1.1.3.2 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/Architect#30]
Notes:
     on startup

crash report:
https://gist.github.com/79f65f9665db4e62f6daa3c0a6b4602e

fml server latest:
https://gist.github.com/9b405c54d4d2f9a91f6679002bfcb0cc

**Comment by fnuecke** [comment]
Should be fixed in 1.1.3.5!
